// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pecrqdynmkgvqiasriwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlY3JxZHlubWtndnFpYXNyaXd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NDE4MjMsImV4cCI6MjA1NzMxNzgyM30.ChokD92odrZwYLaVlB8PB7XbStmTmzVP4MYiKX47mWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);